services:
  postgres:
    container_name: transactional-resilience-postgres
    image: postgres:16
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: resilience
      POSTGRES_USER: resilience
      POSTGRES_PASSWORD: resilience
